<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AydoganERP.Base.Application\AydoganERP.Base.Application.csproj" />
      <ProjectReference Include="..\AydoganERP.Inventory.Domain\AydoganERP.Inventory.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="InventoryManager\Commands\" />
      <Folder Include="InventoryManager\IntegrationHandlers\" />
      <Folder Include="InventoryManager\Queries\" />
    </ItemGroup>

</Project>
